basePath: /
definitions:
  handlers.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  handlers.OrderRequest:
    properties:
      country_code:
        type: string
      items:
        items:
          properties:
            product_id:
              type: string
            quantity:
              type: integer
          type: object
        type: array
    type: object
  handlers.OrderResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/handlers.orderItemReply'
        type: array
      order_id:
        type: string
      total_price:
        type: number
      total_vat:
        type: number
    type: object
  handlers.ProductResponse:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      price_with_vat:
        type: number
      vat:
        type: number
    type: object
  handlers.orderItemReply:
    properties:
      name:
        type: string
      product_id:
        type: string
      quantity:
        type: integer
      unit_price:
        type: number
      vat:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: API per la gestione degli ordini del carrello acquisti
  title: Purchase Cart Service API
  version: "1.0"
paths:
  /api/v1/orders:
    get:
      description: Recupera una lista di tutti gli ordini
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.OrderResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Elenca tutti gli ordini
      tags:
      - Orders
    post:
      consumes:
      - application/json
      description: Crea un nuovo ordine nel sistema
      parameters:
      - description: Dati ordine
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/handlers.OrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.OrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Crea un nuovo ordine
      tags:
      - Orders
  /api/v1/orders/{id}:
    get:
      description: Recupera i dettagli di un ordine utilizzando il suo ID
      parameters:
      - description: ID Ordine
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.OrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Ottieni un ordine per ID
      tags:
      - Orders
  /api/v1/products:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all products
      parameters:
      - description: Country Code for VAT calculation
        in: query
        name: country_code
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.ProductResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get All Products
      tags:
      - Products
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Health check
      tags:
      - health
schemes:
- http
swagger: "2.0"
